### ISSUE TITLE
Ability to Listen to Events

### ISSUE THREAD

**Issue by paulmowat** [harness/ff-nodejs-server-sdk#19]
At the minute I can't see a way to pause execution until the SDK is ready. Could you add in ability to listen to events like the Javascript SDK has.

This would allow us to write a wrapper around this SDK that we could then use within AWS Lambda.

When the Lambda is initialised from a cold start we'd take the small time hit to wait till it's ready before executing our code, but after that we'd be good for subsequent executions.

Events
-------
cf.on(Event.READY, flags => {
  // Event happens when connection to server is established
  // flags contains all evaluations against SDK key
})

cf.on(Event.CHANGED, flagInfo => {
  // Event happens when a changed event is pushed
  // flagInfo contains information about the updated feature flag
})

cf.on(Event.DISCONNECTED, () => {
  // Event happens when connection is disconnected
})

cf.on(Event.ERROR, error => {
  // Event happens when connection some error has occurred
})

**Comment by enver-bisevac** [comment]
In the latest version 1.1.0 there is waitForInitialization function, example:
```
const { Client } = require('ff-nodejs-server-sdk');

console.log('Starting application');
const client = new Client('your sdk key');
client
  .waitForInitialization()
  .then(() => {
    setInterval(async () => {
      const target = {
        identifier: 'harness',
      };
      const value = await client.boolVariation('test', target, false);
      console.log('Evaluation for flag test and target: ', value, target);
    }, 10000);

    console.log('Application started');
  })
  .catch((error) => {
    console.log('Error', error);
  });
```
